export const gridOne ={
     mainHeading: "Academic Institutions",
     caption: "Appointy can help bussiness and insitution in the education, advising and non-profit domain schedule 1:1 sessions, round robin meeting, group discussions",
     icon1: 'Assets/g11.svg' ,
     subHeading1:'Schools',
     content1:  "Schools can make class time tables, schedule resources, organize staff & parent meetings, career counseling etc.  ",
     icon2: 'Assets/g12.svg',
     subHeading2: 'Universities & Colleges',
     content2:  "Institutions can schedule academic counseling, advising sessions, applicant interviews, campus tours, courses. and more  ",
     icon3: 'Assets/g13.svg' ,
     subHeading3:"Profesers & Teachers" ,
     content3:  "Professors can let students book 1:1 classes, doubt clearing sessions. after school activities, project mentoring, and more  ",
     icon4: 'Assets/g14.svg' ,
     subHeading4: "Libraries",
     content4: "school or university libraries can manage bookings of study rooms, computer systems, hourly reading slots. etc. " ,
     icon5: 'Assets/g15.svg' ,
     subHeading5:'Tutors',
     content5:  "Tutors can schedule in-person or online classes, market their business, manage students and more  ",
     icon6: 'Assets/g16.svg',
     subHeading6: 'Students Services',
     content6:  "Students can schedule on campus tech support, repair works, admin enquiries etc. with student services ",
     icon7: 'Assets/g17.svg ',
     subHeading7:"Test Center" ,
     content7:  "Test centers can schedule seats, computers, test taking time-slots and more ",
     icon8: 'Assets/g18.svg' ,
     subHeading8: "Educational Events",
     content8: "Institutions can let attendees reserve a seat for science fairs, art exhibitions, seminars. webinars, conferences. etc " ,
}


export const gridTwo ={
     mainHeading: "Appointy handles your everyday admin so that you can focus on increasing student success",
     caption: "Cost-effective education booking software that streamlines end-to-end operations, reduces no-shows, and ensures that your staff isn't overwhelmed ",
     icon1: 'Assets/Calendar.svg' ,
     subHeading1:'Calender Shedular',
     content1:  "See your entire schedule at a glance with Appointy's easy-to-use calendar with colour-coded tiles for teachers and sessions. Sync schedule with your personal or professional calendars so that you're never double booked ",
     icon2: 'Assets/Class-Reminders.svg',
     subHeading2: 'Class Reminders',
     content2:  "Send automated email and text reminder notifications to students prior to a session. meeting or a class to ensure that they don't miss it. Customize them to add info like room number. location links. etc.  ",
     icon3: 'Assets/RScheduling.svg' ,
     subHeading3:"Resource Sheduling" ,
     content3:  " Lab rooms. sports fields. conference halls, etc. automatically when a session is booked Save time and reduce operational costs that come with manually allocating resources  ",
     icon4: 'Assets/Booking-Settings.svg' ,
     subHeading4: "Booking Automation",
     content4: " Limit the number of meetings and classes you can take in a day/week so that you are not overloaded. Choose how much in advance anyone can book/cancel. set maximum capacity for a class or session, and more " ,
     icon5: 'Assets/g25.svg' ,
     subHeading5:'Staff Managment',
     content5:  "Boost staff productivity and let them view & manage their own schedules and sick Leaves using separate staff towns. Distribute sessions across your team automatically with intelligent staff allocation ",
     icon6: 'Assets/g26.svg',
     subHeading6: 'Online Prepayments',
     content6:  "llow students to pay for your classes/sessions when they boot Require fultibartial fee with our payment integrations with Stripe. Square. and Paypal so that you don't Lose out on last-minute cancellations ",
     icon7: 'Assets/g27.svg ',
     subHeading7:"Reporting & Analytics" ,
     content7:  "Keep track of the number of classes in a week month. sates. staff utilization, and more. Powerful reporting tools help you spot and resolve operational inefficiencies and help optimize your processes ",
     icon8: 'Assets/g28.svg' ,
     subHeading8: "Scheduling Mobail App",
     content8: "Stay on top of upcoming appointments and schedule changes with Appointy's Android & iOS mobile app. You and your staff can manage scheduling, payments, and reminders even when you are away from the desk " ,
}




